name: test

on:
  push:
    branches: ["main"]

  workflow_dispach:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: debian-latest
    steps:
      # ... continue